my_blog/blogapp/urls.py
from . import views
from django.urls import path

app_name = 'blogapp'

urlpatterns = [
    path('about', views.AboutView.as_view(), name='about'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new', views.CreatePostView.as_view(), name='create_post'),
    path('post/<int:pk>/edit', views.PostUpdateView.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    path('drafts', views.DraftListView.as_view(), name='drafts'),
    path('post/<int:pk>/comment', views.add_comment_to_post, name='add_comment'),
    path('comment/<int:pk>/approve/', views.approve_comment, name='approve_comment'),
    path('comment/<int:pk>/remove_comment/', views.remove_comment, name='remove_comment'),
    path('post/<int:pk>/publish', views.post_publish, name='post_publish'),

]


my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls')),
    path('test', views.TestPage.as_view(), name='test'),
    path('thanks', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

]

my_blog/blogapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=1000)
    blog_post = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('blogapp:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comments(models.Model):
    post = models.ForeignKey('blogapp.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=256)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blogapp:post_list')

    def __str__(self):
        return self.text

my_blog/blogapp/forms.py
from django import forms
from .models import Post, Comments


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'title', 'blog_post')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass form-control'}),
            'blog_post': forms.Textarea(attrs={'class': 'editable medium-editor-textarea post-content form-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass form-control'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea form-control'}),
        }

my_blog/blogapp/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.utils import timezone
from django.urls import reverse_lazy
from .models import Post, Comments
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from django.views.generic import (TemplateView, UpdateView,
                                  CreateView, DeleteView,
                                  DetailView, ListView)
from django.utils import timezone
# Create your views here.


class AboutView(TemplateView):
    template_name = 'blogapp/about.html'


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blogapp/post_detail.html'
    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blogapp/post_detail.html'
    form_class = PostForm
    model = Post


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blogapp:post_list')


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blogapp/post_detail.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')


#######################using function based views for comments ###############


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blogapp:post_detail', pk=pk)


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blogapp:post_detail', pk=post.pk)

    else:
        form = CommentForm()
    return render(request, 'blogapp/comment_form.html', {'form': form})


@login_required
def approve_comment(request, pk):
    comment = get_object_or_404(Comments, pk=pk)
    comment.approve()
    return redirect('blogapp:post_detail', pk=comment.post.pk)


@login_required
def remove_comment(request, pk):
    comment = get_object_or_404(Comments, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blogapp:post_detail', pk=post_pk)

my_blog/my_blog/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'


class TestPage(TemplateView):
    template_name = 'test.html'


class ThanksPage(TemplateView):
    template_name = 'thanks.html'


my_blog/blogapp/templates/blogapp/about.html
{% extends 'base.html' %}


{% block title %}
<title>About Page</title>
{% endblock %}


{% block content %}
    <h1>About Michael</h1>
    <p>Thanks for checking this site</p>
{% endblock %}

my_blog/blogapp/templates/blogapp/comment_form.html
{% extends 'base.html' %}


{% block title %}
<title>Comments</title>
{% endblock %}


{% block content %}
    <h1>New comment</h1>
    <form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button class="save btn btn-lg btn-primary" type="submit">Post comment</button>

    </form>
    <script src="">var editor = new MediumEditor('.editable');</script>

{% endblock %}

my_blog/blogapp/templates/blogapp/post_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
  <title>MY Blog</title>
{% endblock %}

{% block content %}
  <h1>Delete {{post.title}}</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object }}</p>
    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="{% url 'blogapp:post_detail' pk=post.pk %}" class="btn btn-primary">Cancel</a>
  </form>

{% endblock %}

my_blog/blogapp/templates/blogapp/post_detail.html
{% extends 'base.html' %}


{% block title %}
  <title>MY Blog</title>
{% endblock %}

{% block content %}
  <h1 class="post-title loader">{{post.title}}</h1>
  {% if post.published_date %}
    <div class="date post-date">
      <p>{{post.published_date}}</p>
    </div>
  {% else %}
    <a class="btn btn-primary" href="{% url 'blogapp:post_publish' pk=post.pk %}">Publish</a>
  {% endif %}
  <p class="post-content">{{post.blog_post|safe|linebreaksbr}}</p>
  {% if user.is_authenticated%}
    <a class="btn btn-primary" href="{% url 'blogapp:edit_post' pk=post.pk %}"> Edit Post</a>
    <a class="btn btn-danger" href="{% url 'blogapp:delete_post' pk=post.pk %}">Delete Post</a>
  {% endif %}
  <hr>
  <a class="btn btn-primary btn-comment" href="{% url 'blogapp:add_comment' pk=post.pk %}">Add Comment</a>

  <div class="container comments">
    {% for comment in post.comments.all %}
      <br>
        {% if user.is_authenticated or comment.approved_comment %}
          {{ comment.created_date}}
            {% if not comment.approved_comment %}
              <a class="btn btn-primary" href="{% url 'blogapp:approve_comment' pk=comment.pk%}"> Approve comment</a>
              <a class="btn btn-danger" href="{% url 'blogapp:remove_comment' pk=comment.pk%}">Delete comment</a>
            {% endif %}
            <p>{{comment.text|safe|linebreaks}}</p>
            <span>{{comment.author}}</span>
        {% endif %}
        {% empty %}
        <p>No comment</p>
    {% endfor %}

  </div>


{% endblock %}

my_blog/blogapp/templates/blogapp/post_draft_list.html
{% extends 'base.html' %}


{% block title %}
<title>Drafts</title>
{% endblock %}


{% block content %}
    {% for post in posts %}
        <div class="post container">
            <p class="date">created {{post.created_date|date "d m y"}}</p>
            <h1><a href="{% url 'blogapp:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
            <p>{{post.blog_post|truncatechars:200}}</p>
        </div>
    {% endfor %}
{% endblock %}

my_blog/blogapp/templates/blogapp/post_form.html
{% extends 'base.html' %}


{% block title %}
  <title>MY Blog</title>
{% endblock %}

{% block content %}
  <h1> New Post</h1>
  <form class="post-form" action="" method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <button class="save btn btn-lg btn-primary" type="submit">Submit</button>
  </form>
  <script src="">var editor = new MediumEditor('.editable');</script>

{% endblock %}

my_blog/blogapp/templates/blogapp/post_list.html
{% extends 'base.html' %}


{% block title %}
  <title>MY Blog</title>
{% endblock %}

{% block content %}
  <div class="centerstage container-fluid">
    {% for post in post_list %}
      <div class="post">
        <h1><a href="{% url 'blogapp:post_detail' pk=post.pk %}">{{post.title}}</a> </h1>
        <div class="date">
          <p>Published on: {{post.published_date|date:"D M Y"}}</p>
        </div>
        <a href="{% url 'blogapp:post_detail' pk=post.pk%}">Comments: {{post.approve_comments.count}}</a>
      </div>

    {% endfor %}
  </div>

{% endblock %}

my_blog/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<!--  medium-->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<!--  custom css-->
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">

<!--  google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Noto+Sans:wght@300&family=Ubuntu&display=swap" rel="stylesheet">
  {%  block title %}
    <title>Base</title>
  {% endblock %}
</head>
<body class="loader">
  <nav class="navbar navbar-expand-lg bg-body-tertiary nav-font custom-navbar">
    <div class="container-fluid">
      <a class="navbar-brand big-brand" href="{% url 'blogapp:post_list' %}">MY-BLOG</a>
      <a class="nav-link" href="{% url 'blogapp:about'%}">About</a>
      <a class="nav-link" href="https://github.com/Ibezimmichael">Github</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogapp:create_post' %}">New Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogapp:drafts'%}">Drafts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
            </li>
            <li class="nav-item">
              <a>Welcome: {{user.username}}</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            {% endif %}
          </ul>
        </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}

    {% endblock %}

  </div>


</body>
</html>

my_blog/templates/test.html
{% extends 'base.html' %}

{% block content %}
  <h1>You are logged in</h1>
{% endblock %}

my_blog/templates/thanks.html
{% extends 'base.html' %}

{% block content %}
  <h1>You are logged out</h1>
{% endblock %}